-- Create the contacts table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  project_type text,
  message text,
  budget text
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Create a policy that allows anyone to insert data (for the contact form)
create policy "Enable insert for all users"
on public.contacts
for insert
with check (true);

-- Create a policy that allows only authenticated users to view data (optional, for your dashboard)
-- For now, we'll allow anon read just so you can verify it easily, but in production you'd want this restricted.
create policy "Enable read access for all users"
on public.contacts
for select
using (true);
